### ISSUE TITLE
Create Admin End for Event control

### ISSUE THREAD

**Issue by panthosarkar** [bipon68/kpi-alumni-frontend#7]
- [x] Add ui for admin 
- [ ] Add new  form design for creating a event 
- [ ] add Api end point for creating and fetching data from database

**Comment by bipon68** [comment]
![newsandevent](https://github.com/user-attachments/assets/f7b7eaa8-c614-44a0-874e-89dbfabb1ae1)

**Comment by panthosarkar** [comment]
@nomangazi @bipon68 What should I use for selecting date?

**Comment by bipon68** [comment]
> @nomangazi @bipon68 What should I use for selecting date?
Please follow-up @nomangazi

**Comment by nomangazi** [comment]
> @nomangazi @bipon68 What should I use for selecting date?

@panthosarkar You can use `yarn add react-datepicker`. Because `react-flatpicker` stops their support. So you use react-datepicker. And create a component in the `lib` folder for reusable.

**Comment by panthosarkar** [comment]
The  backend crud operation has been  done . Now it needs to be intregrated  with the frontend

**Comment by bipon68** [comment]
> The backend crud operation has been done . Now it needs to be intregrated with the frontend

Thank you. Eagerly waiting to see.
